# Generated by Django 4.2.7 on 2025-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installments',
            field=models.IntegerField(default=1),
        ),
    ]
