# Generated by Django 4.2.7 on 2025-11-04 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('bike', 'Vélo'), ('accessory', 'Accessoire'), ('part', 'Pièce détachée'), ('service', 'Service')], default='bike', max_length=20)),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('stock_ville_avray', models.IntegerField(default=0)),
                ('stock_garches', models.IntegerField(default=0)),
                ('alert_stock', models.IntegerField(default=5)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='products_referen_fa31fd_idx'), models.Index(fields=['barcode'], name='products_barcode_d008ac_idx'), models.Index(fields=['name'], name='products_name_6f9890_idx')],
            },
        ),
    ]
